data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
apiVersion: v1
kind: Secret
metadata:
  name: aks
---
data:
  host.master: ZkdwM3FPSy9EWWRNdXMwZnFIeWhtSFdodzBuN3dPb3VvS1lxUk12UTRLQmFReDBIRmJUNTVBPT0=
  host.function.default: NTBlYWJxSWR0akZHb0lLY2RuMGl6UWVBMzFrUjVhdUxhTkF2RlM1eFk2YzExNzRmcDZxQ3BBPT0=
  host.systemKey.default: YWdrcUVaL0dIWTg5UG1VSW5RdE95em9hMlZncWdOTmxCQmszMm1yc1FHU2R5MmV6ZU56NjhBPT0=
  functions.createadvertisement.default: Z2R2NER0Ym1Ca1psekp3SElxVkg5TzZ6SlYwdXVteWQ0MGQ1dFkvS2EwY0VsSTZHWXNNdWRnPT0=
  functions.deleteadvertisement.default: cjlGbmF0SDFremMvRXlDVFY3dU5uRG81OFJuNmFNQVJEcXZWODZjeWs0ckxtQUNkcWZ3MVFBPT0=
  functions.getadvertisement.default: ZzQyRXdUU2FUbS94Zk11ckZUUUdDQTFOTUZ4WkNvV2NPYnpaeTRZNWd6L0NIMlJwenc1YVVBPT0=
  functions.getadvertisements.default: SWRoaldsV1RXREJtWmlFNjlGVDNIWDFWbzlVYzYwaWlCc09kdWVFbUZyTFRhZi91MWFzNEtnPT0=
  functions.getpost.default: RXFqOGRFVU53VXpsd0FqTUtXNTVVaGE4Y2N0V0hMMEdoOHY1Q1I4TnF4cVBvUXNsMjRLWURnPT0=
  functions.getposts.default: Wld3aWdMVnJ0NHNrWkZFSnVKR2FqT0g4cW53VzdOWlc2V0xHZWNqeHR4S0hLbTU1QXl2WHJBPT0=
  functions.updateadvertisement.default: U1IwOEVqcTNZT0dYQ1BQaGpocFcwRjhIL0ZYbWVvZUgwd1kzWVNnRXJjMWY1WEdPZGZtekRBPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-aks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aks-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: aks-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aks-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: aks-http
spec:
  selector:
    app: aks-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-http
  labels:
    app: aks-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-http
  template:
    metadata:
      labels:
        app: aks-http
    spec:
      containers:
      - name: aks-http
        image: ncontainer.azurecr.io/neighborlyimage
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-aks
        envFrom:
        - secretRef:
            name: aks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: aks-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks
  labels:
    app: aks
spec:
  selector:
    matchLabels:
      app: aks
  template:
    metadata:
      labels:
        app: aks
    spec:
      containers:
      - name: aks
        image: ncontainer.azurecr.io/neighborlyimage
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: aks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: aks-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aks
  labels: {}
spec:
  scaleTargetRef:
    name: aks
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---
